### ISSUE TITLE
Eagle files?

### ISSUE THREAD

**Issue by madprogrammer** [DexterInd/BrickPi3#51]
Hi,
I was wondering where are the Eagle files for the schematic and board? Seem to be mentioned on the website: https://www.dexterindustries.com/BrickPi/brickpi-tutorials-documentation/about/design/hardware-design/ but I can only see a schematic PDF.

Are they open source?

**Comment by mattallen37** [comment]
The original BrickPi hardware was open source, but the BrickPi+ and BrickPi3 hardware is not open source.

Are there any specific questions I can answer for you regarding the BrickPi3 hardware?

**Comment by dlech** [comment]
According to LICENSES.md...

> The hardware schematics are released under the Creative Commons Attribution NonCommercial ShareAlike 4.0 License.

Is this correct or should it be changed?

**Comment by mattallen37** [comment]
That is correct. The hardware schematics _are_ released under the [Creative Commons Attribution NonCommercial ShareAlike 4.0 License](https://creativecommons.org/licenses/by-nc-sa/4.0/).

The schematics are released as a PDF, not as an eagle .sch file. This helps to encourage the "nc" (NonCommercial) part of the license (make it harder for someone to try building knock-offs). The eagle .brd file and PCB gerbers are also not available for the same reason.

The schematic was released for reference, not so that someone can build their own BrickPi3.

**Comment by madprogrammer** [comment]
Ok, got it. Though, the original BrickPi repo also seems to lack the .sch and .brd files as of now.

**Comment by mattallen37** [comment]
Yes, they were removed at some point.

**Comment by graykevinb** [comment]
You can however access the eagle files still for the early BrickPi!
https://github.com/DexterInd/BrickPi/commit/0a6fc005c741c9441665a3100aadaf24e4103f8c

On March 21, 2017, at 9:12 AM, Matthew Richardson <notifications@github.com> wrote:

Yes, they were removed at some point.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DexterInd/BrickPi3","title":"DexterInd/BrickPi3","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/DexterInd/BrickPi3">https://github.com/DexterInd/BrickPi3</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mattallen37 in #51: Yes, they were removed at some point."}],"action":{"name":"View Issue","url":"<a href="https://github.com/DexterInd/BrickPi3/issues/51#issuecomment-288090276">https://github.com/DexterInd/BrickPi3/issues/51#issuecomment-288090276</a>"}}}
